# Generated by Django 5.0.3 on 2024-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_chatbox_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='room',
            field=models.CharField(default='1-2', max_length=20),
        ),
    ]
