# Generated by Django 5.0.3 on 2024-03-31 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_grievance_faulty_item_image_alter_demand_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='in_stock',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='offering',
            old_name='in_stock',
            new_name='available',
        ),
        migrations.AddField(
            model_name='grievance',
            name='subject',
            field=models.CharField(default='Item damage', max_length=100),
        ),
        migrations.AddField(
            model_name='grievance',
            name='timeStamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
