# Generated by Django 5.0.3 on 2024-03-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_rename_in_stock_demand_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='timeStamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
