# Generated by Django 5.0.3 on 2024-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_otpverification_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
