# Generated by Django 5.0.3 on 2024-04-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_chatbox_timestamp_alter_deal_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
