# Generated by Django 5.0.3 on 2024-04-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_alter_chatbox_timestamp_alter_deal_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbox',
            options={'ordering': ['-timeStamp']},
        ),
    ]
