# Generated by Django 5.0.3 on 2024-04-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_grievance_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='by',
            new_name='defaulter',
        ),
    ]
