# Generated by Django 5.0.3 on 2024-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_rename_by_grievance_defaulter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='count',
        ),
        migrations.AddField(
            model_name='deal',
            name='grievance_count',
            field=models.IntegerField(default=0),
        ),
    ]
