# Generated by Django 5.0.3 on 2024-04-05 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_remove_grievance_count_deal_grievance_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='grievance_count',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='grievance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
