# Generated by Django 5.0.3 on 2024-04-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_payment_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment_data',
            new_name='Payment',
        ),
    ]
